### ISSUE TITLE
Error when open my export project

### ISSUE THREAD

**Issue by ghost** [overdev/raylib-py#39]
I was finish my game and export it by **pyinstaller**, but when I run the file, it error:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "raylibpy\__init__.py", line 68, in <module>
RuntimeError: Unable to find raylib library ('libraylib_shared.dll').

**Comment by overdev** [comment]
I'm not sure pyinstaller will atomatically recognize the dll importing when generating the exacutable. Maybe you need to add some extra tweaks. If it does not work, you could try [Nuitka](https://nuitka.net/index.html).
