### ISSUE TITLE
pip version import does not work on 64 bit Ubuntu 20.04

### ISSUE THREAD

**Issue by creikey** [overdev/raylib-py#41]
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import raylibpy as r
  File "/home/creikey/Documents/grayviewer/env/lib/python3.8/site-packages/raylibpy/__init__.py", line 71, in <module>
    _rl = CDLL(os.path.join(RAYLIB_BIN_PATH, _lib_filename[_platform]))
  File "/home/creikey/.pyenv/versions/3.8.5/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/creikey/Documents/grayviewer/env/lib/python3.8/site-packages/raylibpy/libraylib.so.2.0.0: wrong ELF class: ELFCLASS32

```

**Comment by int91** [comment]
I'm getting the same error on Fedora Linux

**Comment by overdev** [comment]
I'm not sure if this relates to cytpes or to the binding code.
